import { Stack } from "@chakra-ui/react";
import { motion } from "framer-motion";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

import { Post } from "../atoms/PostAtom";
import CreatePostLink from "../components/Community/CreatePostLink";
import PersonalHome from "../components/Community/PersonalHome";
// import Premium from "../components/Community/Premium";
import Recommendation from "../components/Community/Recommendation";
import PageContent from "../components/Layout/PageContent";
import PostItem from "../components/posts/PostItem";
import PostLoader from "../components/posts/PostLoader";
import { useAuth } from "../contexts/AuthContext";
import useCommunityData from "../hooks/useCommunityData";
import usePosts from "../hooks/usePosts";
import { postService } from "../services/postService";

const Home: NextPage = () => {
  const { user, loading: loadingUser } = useAuth();
  const [loading, setLoading] = useState(false);
  const [hasFetched, setHasFetched] = useState(false);
  const {
    postStateValue,
    setPostStateValue,
    onDeletePost,
    onSelectPost,
    onVote,
  } = usePosts();
  const { communityStateValue } = useCommunityData();

  //const communityStateValue = useRecoilValue(CommunityState);

  useEffect(() => {
    if (loadingUser || hasFetched) return;

  const buildHomeFeed = async () => {
    setLoading(true);
      setHasFetched(true);
    try {
      const response = await postService.getPosts(20, 0);

      const posts: Post[] = response.posts.map((p) => {
        let voteStatus = 0;
        if (p.vote_count !== undefined) {
          voteStatus = p.vote_count;
        }

        const creatorDisplayName =
          p.author?.full_name ||
          p.author?.email?.split("@")[0] ||
          "anonymous";

        const communityName =
          p.community?.name || String(p.subreddit_id || "");

        const communityImageURL = p.community?.avatar || "";

        return {
          id: String(p.id),
          communityId: String(p.subreddit_id || ""),
          communityName,
          creatorId: String(p.author_id),
          creatorDisplayName,
          title: p.title,
          body: p.content ?? "",
          numberOfComments: Number(p.nr_of_comments || 0),
          voteStatus,
          imageURL: p.media?.[0]?.media_url,
          communityImageURL,
          createdAt: p.created_at
            ? ({ seconds: new Date(p.created_at).getTime() / 1000 } as any)
            : ({ seconds: Date.now() / 1000 } as any),
        };
      });

        // Map my_vote vào postVotes
        const postVotes = response.posts
          .filter((p) => p.my_vote !== undefined && p.my_vote !== 0)
          .map((p) => ({
            id: `vote-${p.id}`,
            postId: String(p.id),
            communityId: String(p.subreddit_id || ""),
            voteValue: p.my_vote!,
          }));

      setPostStateValue((prev) => ({
        ...prev,
        posts,
          postVotes: postVotes,
      }));
    } catch (error) {
      console.log("BuildHomeFeed error", error);
        setHasFetched(false); // Reset on error to allow retry
      } finally {
        setLoading(false);
    }
  };

      buildHomeFeed();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loadingUser]);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Reddit Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/header.png" />
      </Head>
      <PageContent>
        <>
          <CreatePostLink />
          {loading ? (
            <PostLoader />
          ) : (
            <Stack>
              {postStateValue.posts.map((post) => (
                <PostItem
                  key={post.id}
                  post={post}
                  onVote={onVote}
                  onDeletePost={onDeletePost}
                  userVoteValue={
                    postStateValue.postVotes.find(
                      (item) => item.postId === post.id
                    )?.voteValue
                  }
                  userIsCreator={String(user?.id) === post.creatorId}
                  onSelectPost={onSelectPost}
                  homePage
                />
              ))}
            </Stack>
          )}
        </>
        <Stack spacing={5}>
          <Recommendation />
          {/* <Premium /> */}
          <PersonalHome />
        </Stack>
      </PageContent>
    </motion.div>
  );
};

export default Home;
