import { doc, getDoc } from "firebase/firestore";
import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import React, { useEffect } from "react";
import { motion } from "framer-motion";
import { useSetRecoilState } from "recoil";
import safeJsonStringify from "safe-json-stringify";

import { Community, CommunityState } from "../../../atoms/CommunitiesAtom";
import About from "../../../components/Community/About";
import CreatePostLink from "../../../components/Community/CreatePostLink";
import Header from "../../../components/Community/Header";
import NotFound from "../../../components/Community/NotFound";
import PageContent from "../../../components/Layout/PageContent";
import Posts from "../../../components/posts/Posts";
import axios from "axios";
import Members from "../../../components/Community/Members";

type CommunityProps = {
  communityData: Community;
};

const CommunityPage: React.FC<CommunityProps> = ({ communityData }) => {
  //console.log(communityData);
  const setCommunityStateValue = useSetRecoilState(CommunityState);

  useEffect(() => {
    setCommunityStateValue((prev) => ({
      ...prev,
      currentCommunity: communityData,
    }));
  }, [communityData]);

  if (!communityData) {
    return <NotFound />;
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Reddit Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/header.png" />
      </Head>
      <Header communityData={communityData} />
      <PageContent>
        <>
          <CreatePostLink />
          <Posts communityData={communityData} />
        </>
        <>
          <About communityData={communityData} />
          <Members communityData={communityData} />
        </>
      </PageContent>
    </motion.div>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  try {
    const { communityId } = context.query;

    const res = await axios.get(
      `${process.env.NEXT_PUBLIC_API_BASE_URL}/api/community/${communityId}`
    );

    return {
      props: {
        communityData: res.data || null,
      },
    };
  } catch (error: any) {
    console.error("GetServerSideProps Error:", error.response?.data || error.message);
    return {
      props: {
        communityData: null,
      },
    };
  }
}

export default CommunityPage;