import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import React, { useEffect } from "react";
import { motion } from "framer-motion";
import { useSetRecoilState } from "recoil";
import safeJsonStringify from "safe-json-stringify";

import { Community, CommunityState } from "../../../atoms/CommunitiesAtom";
import About from "../../../components/Community/About";
import CreatePostLink from "../../../components/Community/CreatePostLink";
import Header from "../../../components/Community/Header";
import NotFound from "../../../components/Community/NotFound";
import PageContent from "../../../components/Layout/PageContent";
import Posts from "../../../components/posts/Posts";
import { communityService } from "../../../services/communityService";

type CommunityProps = {
  communityData: Community;
};

const CommunityPage: React.FC<CommunityProps> = ({ communityData }) => {
  //console.log(communityData);
  const setCommunityStateValue = useSetRecoilState(CommunityState);

  useEffect(() => {
    setCommunityStateValue((prev) => ({
      ...prev,
      currentCommunity: communityData,
    }));
  }, [communityData, setCommunityStateValue]);

  if (!communityData) {
    return <NotFound />;
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Reddit Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/header.png" />
      </Head>
      <Header communityData={communityData} />
      <PageContent>
        <>
          <CreatePostLink />
          <Posts communityData={communityData} />
        </>
        <>
          <About communityData={communityData} />
        </>
      </PageContent>
    </motion.div>
  );
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  try {
    const id = context.query.communityId as string;
    const dto = await communityService
      .getCommunityById(id)
      .catch(() => null);

    return {
      props: {
        communityData: dto
          ? JSON.parse(
              safeJsonStringify((() => {
                const backendId = dto.community_id ?? dto.id;
                // Use ID as the identifier for routing
                const slug = backendId ? String(backendId) : String(id);

                let typeId = dto.type_id ?? dto.communityType?.type_id;

                const typeString =
                  (dto as any).type || dto.communityType?.type;
                if (!typeId && typeString) {
                  const t = typeString.toLowerCase();
                  if (t === "private") typeId = 1;
                  else if (t === "public") typeId = 2;
                  else if (t === "restricted") typeId = 3;
                }

                return {
                  id: slug,
                  backendId,
                  name: dto.name, 
                  creatorId: String(dto.created_by || ""),
                  numberOfMembers:
                    typeof (dto as any).members === "number"
                      ? (dto as any).members
                      : 0,
                  privacyType: "public",
                  createdAt: dto.created_at
                    ? new Date(dto.created_at)
                    : undefined,
                  imageURL: dto.avatar,
                  typeId,
                } as Community;
              })())
            )
          : "",
      },
    };
  } catch (error) {
    console.log("GetServerSideProps Error", error);
  }
}
export default CommunityPage;
